### ISSUE TITLE
Spike: playground examples are a big resource hog

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina.io#1332]
## Summary

As a visitor of the site I want to load our playground examples faster so that I can view content on all pages, on any device, with slower internet connections. 

### Expected Results

Deliver findings on:
- Why is the bundle size so large for playgrounds?
- Can it be improved with the current playground?
- Would it be improved by using a more containerized solution like Sandpack? 
- If this cannot be improved at all, how can our docs be less reliant on these playgrounds?

### Notes

For example, [this page](https://tina.io/docs/reference/types/boolean/) loads > 50mb, with only 2 playgrounds

This is an issue because: 
- We're currently relying on the playgrounds for delivering important info:
e.g: The boolean doc above shows no code-examples outside the playground.

- I'm guessing page loads are pretty painful on slower connections

- When loading a page with 5 playgrounds, it consistently crashed my mobile browser. 

These playgrounds could be a great tool, but we're a bit capped by their resource usage

**Comment by jeffsee55** [comment]
Since these are iframes each one loads the resources themselves. Right now they're in their own repo because Monaco editor can be tricky to work with, but we should be able to get them to build with Next.js and move them over to the tina.io repo. when we do that we can embed these as JSX components instead. 

Having said that, they still need to load esbuild.wasm and typescript (and other monaco-related resources). I think it'll be somewhat resource intensive no matter what, but not more than Sandpack. 

And this initially was Sandpack, but we do some tricky things here that are more difficult with an external hosted version of the code.

**Comment by jamespohalloran** [comment]
The react-beta docs have Sandpack, and they load 5 examples, and it's a pretty reasonable initial page load. It does seem to load more as you scroll, not 100% if that's related to the sandboxes or not, but still lightweight enough to load on mobile. 
https://beta.reactjs.org/learn
