### ISSUE TITLE
Document how/when to use "templates" instead of "fields"

### ISSUE THREAD

**Issue by jamespohalloran** [tinacms/tina.io#1333]
## Summary

We should document how/when to use "templates" instead of fields. It looks like when you use multiple templates, you need to specify the template name in the query (see [here](https://github.com/tinacms/tinacms/issues/2904)), but to my knowledge, that's not required when using `fields` instead of `templates`?

## Expected results

- This info should likely be in our schema reference documentation
- [This page](https://tina.io/docs/graphql/queries/get-document/) include the schema its based off of (or propose a different page/area to put this)
- Explain how to query when using one template vs multiple.

**Comment by jeffsee55** [comment]
> but to my knowledge, that's not required when using fields instead of templates

Yes that's right.

I think the only 2 cents I can add about _when_ to use this is that you might want to use it when you consider documents to be alike in a logical sense, but the shape of the documents differs. Eg. a `post` collection with `videoPost` and `longForm` post templates.

(Though you could just as easily nest the fields in an `object` instead)

---

Side note: the real reason is because Forestry projects have this shape, might be worth revisiting deprecating this behavior once we land on a solid migration story for those projects.

**Comment by gitsstewart** [comment]
Back to OnDeck in favor of isTitle docs first
