### ISSUE TITLE
Docs should mention TinaCMS expects .md or .mdx file extension

### ISSUE THREAD

**Issue by jamtur01** [tinacms/tina.io#1671]
My posts have the file extension: `.markdown` and when I run Tina it doesn't pick up any of my posts. I worked out that I needed to rename them all to `.md` for Tina to pick them up.

**Comment by cassidoo** [comment]
Hmm I think this is actually a bug in the CMS itself, because it seems to expect `.markdown` files at least in some spots:
https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/database/util.ts#L63
https://github.com/tinacms/tinacms/blob/main/packages/%40tinacms/graphql/src/database/util.ts#L99

**Comment by jamtur01** [comment]
Yeah, I had a poke through the code and couldn't spot anything but new to the codebase so 🤷🏻 probably missed something.

**Comment by kldavis4** [comment]
I believe the issue might be that you need to specify `format: "markdown"` on the collection in the schema in order for it to correctly detect the files.
