### ISSUE TITLE
💄 Bookings page

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#1876]
### 🩸 Pain

Currently the bookings option to select from a timezone is only from an in-site modal.
I would like to have a fixed link that I can share through emails and newsletters that allows me to link directly to a "select your timezone" option.

### 💼 Tasks 

- [x] Create a Book a Demo page that has options to book that match the modal

### ✅ Acceptance Criteria 

To be checked by Landon & Levi

### 📸 Screenshots 

![image](https://github.com/tinacms/tina.io/assets/78135895/21871064-f116-40c5-9b7d-eafdb38098d5)
Modal info to be put on a page.

Cc: 
@landonmaxwell @joshberman1 
@Levijj22

**Comment by joshbermanssw** [comment]
✅ Done 
- Refactored Booking Demo Modal to use a graphql query so that the DemoForm Modal and Bookings component use the same shared data from the new meetingsList collection 

![Screenshot 2024-07-15 at 12 26 52 PM](https://github.com/user-attachments/assets/177327d9-c10f-4504-abd0-cc7baae2fb97)
**Figure: 💄/meetings page**
