### ISSUE TITLE
💄 Tina Docs - Pagination 

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#1929]
### 🩸 Pain

When a docs page does not have a forward or backward link, the pagination looks broken (see screenshot below)

### 💡 Suggested Solution

Designer approved UI for pagination field

### 💼 Tasks 

- [x] Collaborate with designer for paginaiton
- [x] Implement 

### ✅ Acceptance Criteria 

- [x] Test passed by designer 

### 📸 Screenshots 

<img width="1049" alt="Screenshot 2024-07-22 at 12 04 34 PM" src="https://github.com/user-attachments/assets/8f597b0e-624a-4b9f-8e41-cd014dfe91af">

**Figure: ❌ Pagination looks broken **

Cc: @bradystroud @bettybondoc

**Comment by bettybondoc** [comment]
cc @joshbermanssw @landonmaxwell

Expected Behaviour for Pagination:

1. Make width consistent for Previous and Next blocks

2. If only one control is available (either Previous or Next), hide the unavailable block, but do not expand the remaining block to full-width
- On the first page, there should be no Previous button (do not extend Next)
- On the last page, there should be no Next button (do not extend Previous)
- Rationale: Users expect the Previous button on the left and the Next button on the right. If the Next button extends to the left when Previous is hidden, users might mistakenly click it and navigate forward unintentionally

3. Make sure pagination is present on all pages

4. Make sure pagination looks consistent across all pages (e.g., for the Product Tour, ensure the pagination is not full-width)
Note: Avoid Overlapping Elements: Ensure that no elements overlap with the pagination controls

5. Ensure the pagination follows the logical order of the table of contents (sidebar)



![Image](https://github.com/user-attachments/assets/49ccdc7b-a621-46d8-a67a-5d69e693959c)

**Figure 1: Inconsistent width for the pagination blocks**



![Image](https://github.com/user-attachments/assets/2e634759-4ce5-40da-a4a4-3038a3e780b7)

**Figure 2: Available block is extended to full-width**



![Image](https://github.com/user-attachments/assets/51b2923b-6be9-4053-99ec-c2162cf69dd8)

**Figure 3: This page does not have pagination**



![Image](https://github.com/user-attachments/assets/2570c5b6-fa78-4439-984f-885a594dcec4)

**Figure 4: Image is overlapping  with pagination**





![Image](https://github.com/user-attachments/assets/9cdba03e-1927-4735-ad30-f9fea51de5e4)



**Figure 5: Next page should be "Framework-Specific Guides"**

**Comment by joshbermanssw** [comment]
Done and Live 

![Image](https://github.com/user-attachments/assets/6874ee59-db18-4837-8fdc-bcfe6146a375)

**Figure: ✅ Test passed design by @bettybondoc **
