### ISSUE TITLE
🧠 Spike - Investigate Graphql and Graphiql endpoints

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2001]
We have two old packages which need to be removed from the project. They are `@tinacms/datalayer-old` and `@tinacms/graphql-old` they are only used in two endpoints, `/graphiql` and `/graphql`. The graphiql endpoint uses deprecated custom methods to spin up a mock db in order to use graphql queries. 

This PBI is to investigate our options with refactoring this endpoint.

Possibilities that have been reccomended;
- [ ] express + graphql https://graphql.org/graphql-js/running-an-express-graphql-server/
- [x] removing graphiql ide and just using screenshots
- [ ] Some other interactive mdx component

**Comment by joshbermanssw** [comment]
Update - @isaaclombardssw has now removed the graphiql endpoint. Still a mystery what the graphql endpoint is used for and what is hitting it.

**Comment by isaaclombardssw** [comment]
Alright so the "graphql" API in `pages/api/graphql.ts` possibly isn't being called at the moment (since removing the graphiql components). 

Based on my understanding after talking to @jeffsee55, it's actually a implementation of a custom/run-time graphql data store that users could use in the docs as a more flexible playground.

Pending approval from @Marxoz, we should try removing it.

**Comment by isaaclombardssw** [comment]
Done. We've deleted the packages – the PR #2236 should be reverted if this causes issues
