### ISSUE TITLE
🐛 Introduction to TinaCMS - cannot reach last section

### ISSUE THREAD

**Issue by bradystroud** [tinacms/tina.io#2211]
### 🐛 Describe the Bug
https://tina.io/docs/product-tour/

This page has a scrolling effect that highlights a single section and shows the related code example.
The last section never becomes highlighted :(

Some users cannot see the last 2 sections, so am guessing it depends on screen size

### 🧑‍💻 Reproduction Steps
1. Go to https://tina.io/docs/product-tour/
2. Scroll to bottom 

![Image](https://github.com/user-attachments/assets/165301b3-b6c4-4d0e-a5af-dc3f36cf79f3)

### 🎯 Expected Behaviour 
I can see all the examples

### 💼 Tasks
- [ ]  Investigate and fix

### ✅ Acceptance Criteria 
I highlight all the sections and see all examples

Cc: 
@wicksipedia @adamcogan @Marxoz

**Comment by isaaclombardssw** [comment]
Done – the previous implementation was comparing the window scroll and heading offset pixel values (with a magic number to make it more consistent). This scales of each were changing w.r.t browser window size.

This has been updated so that both are relative, measured in ratios, and can be compared.
