### ISSUE TITLE
💄Recipe Component

### ISSUE THREAD

**Issue by joshbermanssw** [tinacms/tina.io#2359]
cc: @bettybondoc @Marxoz 

Moving on from the PoC of [✨ POC - Recipes in Tina](https://github.com/tinacms/tina.io/issues/2320) since we got approved to create this

**Tasks**
- [x] Designer to create the design of the recipe component 
- [x] Developer to implement

**Comment by bettybondoc** [comment]
cc @Marxoz @landonmaxwell @joshbermanssw @adamcogan 

1. Test Please
Notes:
- Set max height so that component fits the screen at all times. Handle overflow with visual cues (gradient and arrow) so people know there's more content
- Clicking on "Copy" will trigger an inline toast
- Toggling on "Wrap" will enable text wrap to make code more readable

🎉 Test passed by @tiagov8 

![Image](https://github.com/user-attachments/assets/5309b130-691e-42c9-b42f-4f7a346ddf82)
**Figure: Mobile Version - [Prototype](https://www.figma.com/proto/qFedRo7Xsc9oexI2IoPbFG/Tina.io-Design-Library?node-id=72-6594&node-type=frame&t=wKBl7lXND659sna1-0&scaling=scale-down-width&content-scaling=fixed&page-id=1%3A3&starting-point-node-id=72%3A6594&show-proto-sidebar=1&hide-ui=1)**

![Image](https://github.com/user-attachments/assets/be69d386-210c-4f0b-8d8b-84db6e57e364)
**Figure: Desktop Version - [Prototype](https://www.figma.com/proto/qFedRo7Xsc9oexI2IoPbFG/Tina.io-Design-Library?node-id=22-324&node-type=frame&t=wKBl7lXND659sna1-0&scaling=scale-down-width&content-scaling=fixed&page-id=1%3A3&starting-point-node-id=22%3A324&hide-ui=1)**

**Comment by bettybondoc** [comment]
Test passed by @Marxoz.

Take it away, @joshbermanssw 🚀

**Comment by joshbermanssw** [comment]
Removed task 'Record done video' moved to its own PBI #2429

**Comment by joshbermanssw** [comment]
✅ Done and live
