### ISSUE TITLE
⛓️‍💥 Tina.io broken links - create redirects & fix links

### ISSUE THREAD

**Issue by landonmaxwell** [tinacms/tina.io#2576]
There are a number of Tina pages that are showing a 404 result.
This could be from an outdated sitemap, or moved / deleted pages.

[tina.io_internal_broken_links_20241204.xlsx](https://github.com/user-attachments/files/18001182/tina.io_internal_broken_links_20241204.xlsx)

Pages with 4XX Status e.g. (Tina pages that are broken/no longer exist):
1. Create 301 redirects where necessary

Pages with Broken Links e.g. (pages that link out to a broken page)
2. Update the links to direct to the appropriate page

Backlink Errors e.g. (external sites referring to broken Tina links)
3. Check if any pages need redirects
Note: this should mostly be resolved by the redirects

**Comment by joshbermanssw** [comment]
<img width="726" alt="Screenshot 2024-12-16 at 5 17 14 pm" src="https://github.com/user-attachments/assets/73728b04-4b0b-4ff5-8e7d-c93a01f91d07" />

**Figure: 😢 SemRush audit before**

<img width="698" alt="Screenshot 2024-12-16 at 5 17 37 pm" src="https://github.com/user-attachments/assets/a290cb3f-36ce-4219-90d0-95c99b5159dd" />

**Figure: 😁 SemRush audit AFTER**

_Note two of the pages returning 4XX and 2 internal link issues were fixed in #2604_
