### ISSUE TITLE
🐛 Tina.io not rendering correctly on IOS 18.1.1

### ISSUE THREAD

**Issue by Marxoz** [tinacms/tina.io#2592]
On safari (iOS) – we've been encountering a bug which cause Tina.io to re-render a number of times and eventually show "a problem repeatedly occurred" alongside a white screen.

**Comment by isaaclombardssw** [comment]
This is a story in 3 parts...

Diagnostics info – from inspection data, a couple of things were clear. The page was re-retrieving the same data a number of times (indicative of a hydration error or something similar), webm packets were inconsistently failing, and there weren't any helpful errors or warnings (some unrelated metric webhook failures, ex. google tag due to using local development).

Part 1 – the initial fix, last week I submitted a PR which seemingly solved this on test devices – see https://github.com/tinacms/tina.io/pull/2599

There was a file which didn't match the the naming of the local repo file.

Part 2 – optimisations, I removed preloading for the videos and made them play-in line (this also improved the user experience)

Part 3 (current) – it seems gifs are a viable alternative for mobile, albeit a lot larger in size. We'll move to them for the time being. (showing conditionally, to keep webms for desktop).

**Comment by isaaclombardssw** [comment]
Part 4 – gifs started showing similar errors, so we're now removing images altogether for that component on mobile devices only. The cards will still be shown without the videos.

**Comment by isaaclombardssw** [comment]
Done – on mobile you'll see the below UI instead, to circumvent the video issue.

![Image](https://github.com/user-attachments/assets/5b3271ac-ee53-4061-a276-812310e84832)

**Comment by isaaclombardssw** [comment]
This problem has come up again (incredible intermittently), attempted fix #2771
